language: c

matrix:
  include:
    # Test using python 3.8 on Linux and OSX
    - os: linux
      env: PYTHON_VERSION=3.8
    - os: osx
      env: PYTHON_VERSION=3.8
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

addons:
  apt:
    packages:
    - libfftw3-dev
    - libblas-dev
    - liblapack-dev
    - g++
    - gfortran
    - tcsh
  homebrew:
    packages:
    - fftw
    - wget
    update: true

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
      export FFTW="/usr/local";
    else
      export OS="Linux";
      export FFTW="/usr/local";
    fi

    wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -u -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  #- conda config --append channels conda-forge

  - conda create -q -n test-environment -c conda-forge
        python=$PYTHON_VERSION
        numpy
        scipy
        matplotlib=3.3.*
        jupyter
        astropy
        xarray
        requests
        cartopy
        pygmt
        gmt
        pooch
        tqdm
        palettable
  - conda activate test-environment

  # Conda info
  - conda list -n test-environment
  - conda info -a

  # Install pyshtools
  - pip install --no-deps .

script:
  - python examples/notebooks/test_notebooks.py
  - export MPLBACKEND=Agg
  - make -C examples/python -f Makefile no-timing
  - mkdir empty && cd empty
  - python -c "import pyshtools"

notifications:
    email: false
