channels:
    - conda-forge
dependencies:
    - fftw>=3.3.8
    - liblapack>=3.8
    - numpy
    - scipy>=0.14.0
    - matplotlib-base>=3.3
    - astropy
    - xarray
    - requests
    - pooch>=1.1
    - tqdm
    - cartopy>=0.18.0
    - gmt>=6.1.1
    - pygmt>=0.2.0
    - palettable>=3.3
    - jupyter
    - pypandoc
    - flake8
    - pip
