channels:
    - conda-forge
dependencies:
    - pkg-config
    - fftw>=3.3.8
    - blas-devel>=3.8
    - numpy
    - scipy>=0.14.0
    - matplotlib-base>=3.3
    - astropy>=4.0
    - xarray
    - requests
    - pooch>=1.1
    - tqdm
    - cartopy>=0.18.0
    - gmt>=6.1.1
    - pygmt>=0.3.0
    - palettable>=3.3
    - jupyter
    - pip
    - ducc0>=0.15
    - flake8
