repository: SHTOOLS/SHTOOLS

encoding: UTF-8

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: SHTOOLS
# this appears on the top navigation bar next to the home button

site_title: SHTOOLS - Spherical Harmonic Tools
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: SHTOOLS
# this appears in the footer

github_editme_path: SHTOOLS/SHTOOLS/blob/develop/docs
# if you're using GitHub, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

github_fdoc_editme_path: SHTOOLS/SHTOOLS/tree/develop/src/fdoc
github_pydoc_editme_path: SHTOOLS/SHTOOLS/tree/develop/src/pydoc
# These are the paths for the origin Fortran and Python documentation files.

disqus_shortname: 
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

google_analytics: 
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .gitignore
  - vendor
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: SHTOOLS

feedback_email: mark.wieczorek@oca.eu
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

feedback_text:
# if you uncomment the previous line, it changes the Feedback text

feedback_link:
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
#  tooltips:
#    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: mydoc_sidebar
      topnav: topnav

# these are defaults used for the frontmatter for these file types

sidebars:
- mydoc_sidebar
- fortran_sidebar

description: "SHTOOLS/pyshtools is an archive of Fortran 95 and Python software that can be used to perform spherical harmonic transforms, multitaper spectral analyses on the sphere, expansions of functions into Slepian bases, and standard operations on global gravitational and magnetic field data."
# the description is used in the feed.xml file

encoding: utf-8

# needed for sitemap.xml file and github pages
url : https://shtools.github.io/SHTOOLS
baseurl: /SHTOOLS

plugins:
  - jekyll-github-metadata
