name: Upload Python Package to PYPI

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v1
      with:
        python-version: 3.8
        channels: conda-forge
        auto-update-conda: true
        miniconda-version: "latest"
        activate-environment: pypi

    - name: Set up Conda environment
      shell: bash -l {0}
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda install -q -n pypi python=3.8 \
                                 fftw \
                                 liblapack \
                                 openblas \
                                 numpy \
                                 setuptools \
                                 pypandoc \
                                 versioneer \
                                 twine
        conda list -n pypi

    - name: Build and publish
      env:
        # PYPI repository
        # TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        # TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        # PYPITEST repository
        TWINE_USERNAME: ${{ secrets.PYPITEST_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPITEST_PASSWORD }}
        TWINE_REPOSITORY_URL: 'https://test.pypi.org/legacy/'
      shell: bash -l {0}
      run: |
        conda env list
        python setup.py sdist
        twine upload dist/*
