name: Upload Python Package to PYPI

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        mamba-version: "*"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true
        miniconda-version: "latest"
        activate-environment: pypi

    - name: Set up Conda environment
      shell: bash -l {0}
      run: |
        mamba config --set always_yes yes --set changeps1 no
        mamba install -q -n pypi blas-devel \
                                 fftw \
                                 meson-python \
                                 numpy \
                                 pkg-config \
                                 setuptools_scm \
                                 jupyter \
                                 build \
                                 twine
        mamba list -n pypi

    - name: Build
      env:
      shell: bash -l {0}
      run: |
        mamba env list
        python -m build -s

    - name: Upload release to PyPI
      environment: release
      permissions:
        id-token: write
      steps:
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1

    - name: Trigger a build on the SHTOOLS/build-shtools repo
      run: |
        curl -X POST \
        https://api.github.com/repos/SHTOOLS/build-shtools/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.ACCESS_TOKEN }} \
        --data '{"event_type": "New pyshtools release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

    - name: Download tarball archive
      uses: carlosperate/download-file-action@v2
      id: download-tarball
      with:
        file-url: 'https://github.com/SHTOOLS/SHTOOLS/archive/${{ env.RELEASE_VERSION }}.tar.gz'

    - name: Upload tarball as release asset
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["${{ steps.download-tarball.outputs.file-path }}"]'
